const institutions = [
  "Baptist Outreach Services-AL",
  "Brookwood Baptist Health-AL",
  "Cahaba Medical Care-AL",
  "Crestwood Medical Center",
  "East Alabama Med Ctr",
  "Jack Hughston Memorial Hosp-AL",
  "Jackson Hospital & Clinic-AL",
  "North Alabama Med Ctr",
  "Southeast Health-AL",
  "St Vincents East-AL",
  "Thomas Hospital-AL",
  "U Alabama CCHS-Tuscaloosa",
  "U Alabama Med Ctr-Birmingham",
  "U Alabama SOM-Huntsville",
  "U Alabama SOM-Montgomery",
  "U South Alabama Hospitals",
  "UAB Selma Fam Med Res-AL",
  "Providence Hospital-AK",
  "Abrazo Health Network-AZ",
  "Barrow Neurological Inst at SJHMC-AZ",
  "Creighton University-AZ",
  "Dignity East Valley-AZ",
  "HonorHealth-AZ",
  "MHC Healthcare-AZ",
  "Mayo Clinic School of Grad Med Educ-AZ",
  "Midwestern University OPTI-AZ",
  "North Country HealthCare-AZ",
  "Phoenix Childrens Hospital-AZ",
  "Tucson Hospitals Med Ed-AZ",
  "U Arizona COM-Phoenix",
  "U Arizona COM-South Campus",
  "U Arizona COM-Tucson",
  "Yuma Regional Med Ctr-AZ",
  "Arkansas Coll Osteo Med",
  "Baptist Health-AR",
  "Baptist Mem Med Education-AR",
  "CHI St Vincent Hot Springs-AR",
  "Conway Reg Health Sys-AR",
  "St Bernards Med Ctr-AR",
  "U Arkansas COM-Little Rock",
  "U Arkansas-Fayetteville Comm Progs",
  "UAMS Regional Centers-AR",
  "Unity Health-AR",
];

export default institutions;
