import * as React from "react";
import { GridProps, SelectFieldProps, SwitchFieldProps, TextFieldProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type ValidationResponse = {
    hasError: boolean;
    errorMessage?: string;
};
export declare type ValidationFunction<T> = (value: T, validationResponse: ValidationResponse) => ValidationResponse | Promise<ValidationResponse>;
export declare type UserProfileCreateFormInputValues = {
    sortType?: string;
    isProfile?: boolean;
    step2CSPathway?: string;
    schoolRanking?: string;
    yearOfGraduation?: number;
    monthsOfUSCE?: number;
    ecfmgCertified?: boolean;
    visaRequired?: boolean;
    location?: string;
    graduateType?: string;
    medicalDegree?: string;
    codeName?: string;
    step1ScorePass?: boolean;
    step1Score?: number;
    step2Score?: number;
    step3Score?: number;
    comlex1ScorePass?: boolean;
    comlex2Score?: number;
    redFlags?: boolean;
    redFlagsExplanation?: string;
    aoa?: boolean;
    sigmaSigmaPhi?: boolean;
    goldHumanism?: boolean;
    numPublications?: number;
    numWorkExperiences?: number;
    numVolunteerExperiences?: number;
    classRank?: string;
    otherDegrees?: string;
    numApplications?: number;
    numInterviews?: number;
    numWithdrawn?: number;
    numRejected?: number;
    numWaitlisted?: number;
    applicationYear?: number;
    ownerAccount?: string;
    isProfileString?: string;
};
export declare type UserProfileCreateFormValidationValues = {
    sortType?: ValidationFunction<string>;
    isProfile?: ValidationFunction<boolean>;
    step2CSPathway?: ValidationFunction<string>;
    schoolRanking?: ValidationFunction<string>;
    yearOfGraduation?: ValidationFunction<number>;
    monthsOfUSCE?: ValidationFunction<number>;
    ecfmgCertified?: ValidationFunction<boolean>;
    visaRequired?: ValidationFunction<boolean>;
    location?: ValidationFunction<string>;
    graduateType?: ValidationFunction<string>;
    medicalDegree?: ValidationFunction<string>;
    codeName?: ValidationFunction<string>;
    step1ScorePass?: ValidationFunction<boolean>;
    step1Score?: ValidationFunction<number>;
    step2Score?: ValidationFunction<number>;
    step3Score?: ValidationFunction<number>;
    comlex1ScorePass?: ValidationFunction<boolean>;
    comlex2Score?: ValidationFunction<number>;
    redFlags?: ValidationFunction<boolean>;
    redFlagsExplanation?: ValidationFunction<string>;
    aoa?: ValidationFunction<boolean>;
    sigmaSigmaPhi?: ValidationFunction<boolean>;
    goldHumanism?: ValidationFunction<boolean>;
    numPublications?: ValidationFunction<number>;
    numWorkExperiences?: ValidationFunction<number>;
    numVolunteerExperiences?: ValidationFunction<number>;
    classRank?: ValidationFunction<string>;
    otherDegrees?: ValidationFunction<string>;
    numApplications?: ValidationFunction<number>;
    numInterviews?: ValidationFunction<number>;
    numWithdrawn?: ValidationFunction<number>;
    numRejected?: ValidationFunction<number>;
    numWaitlisted?: ValidationFunction<number>;
    applicationYear?: ValidationFunction<number>;
    ownerAccount?: ValidationFunction<string>;
    isProfileString?: ValidationFunction<string>;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type UserProfileCreateFormOverridesProps = {
    UserProfileCreateFormGrid?: PrimitiveOverrideProps<GridProps>;
    sortType?: PrimitiveOverrideProps<TextFieldProps>;
    isProfile?: PrimitiveOverrideProps<SwitchFieldProps>;
    step2CSPathway?: PrimitiveOverrideProps<SelectFieldProps>;
    schoolRanking?: PrimitiveOverrideProps<SelectFieldProps>;
    yearOfGraduation?: PrimitiveOverrideProps<TextFieldProps>;
    monthsOfUSCE?: PrimitiveOverrideProps<TextFieldProps>;
    ecfmgCertified?: PrimitiveOverrideProps<SwitchFieldProps>;
    visaRequired?: PrimitiveOverrideProps<SwitchFieldProps>;
    location?: PrimitiveOverrideProps<TextFieldProps>;
    graduateType?: PrimitiveOverrideProps<SelectFieldProps>;
    medicalDegree?: PrimitiveOverrideProps<SelectFieldProps>;
    codeName?: PrimitiveOverrideProps<TextFieldProps>;
    step1ScorePass?: PrimitiveOverrideProps<SwitchFieldProps>;
    step1Score?: PrimitiveOverrideProps<TextFieldProps>;
    step2Score?: PrimitiveOverrideProps<TextFieldProps>;
    step3Score?: PrimitiveOverrideProps<TextFieldProps>;
    comlex1ScorePass?: PrimitiveOverrideProps<SwitchFieldProps>;
    comlex2Score?: PrimitiveOverrideProps<TextFieldProps>;
    redFlags?: PrimitiveOverrideProps<SwitchFieldProps>;
    redFlagsExplanation?: PrimitiveOverrideProps<TextFieldProps>;
    aoa?: PrimitiveOverrideProps<SwitchFieldProps>;
    sigmaSigmaPhi?: PrimitiveOverrideProps<SwitchFieldProps>;
    goldHumanism?: PrimitiveOverrideProps<SwitchFieldProps>;
    numPublications?: PrimitiveOverrideProps<TextFieldProps>;
    numWorkExperiences?: PrimitiveOverrideProps<TextFieldProps>;
    numVolunteerExperiences?: PrimitiveOverrideProps<TextFieldProps>;
    classRank?: PrimitiveOverrideProps<SelectFieldProps>;
    otherDegrees?: PrimitiveOverrideProps<TextFieldProps>;
    numApplications?: PrimitiveOverrideProps<TextFieldProps>;
    numInterviews?: PrimitiveOverrideProps<TextFieldProps>;
    numWithdrawn?: PrimitiveOverrideProps<TextFieldProps>;
    numRejected?: PrimitiveOverrideProps<TextFieldProps>;
    numWaitlisted?: PrimitiveOverrideProps<TextFieldProps>;
    applicationYear?: PrimitiveOverrideProps<TextFieldProps>;
    ownerAccount?: PrimitiveOverrideProps<TextFieldProps>;
    isProfileString?: PrimitiveOverrideProps<TextFieldProps>;
} & EscapeHatchProps;
export declare type UserProfileCreateFormProps = React.PropsWithChildren<{
    overrides?: UserProfileCreateFormOverridesProps | undefined | null;
} & {
    clearOnSuccess?: boolean;
    onSubmit?: (fields: UserProfileCreateFormInputValues) => UserProfileCreateFormInputValues;
    onSuccess?: (fields: UserProfileCreateFormInputValues) => void;
    onError?: (fields: UserProfileCreateFormInputValues, errorMessage: string) => void;
    onChange?: (fields: UserProfileCreateFormInputValues) => UserProfileCreateFormInputValues;
    onValidate?: UserProfileCreateFormValidationValues;
} & React.CSSProperties>;
export default function UserProfileCreateForm(props: UserProfileCreateFormProps): React.ReactElement;
